### ISSUE TITLE
Yawrate/ NBT Entrynav

### ISSUE THREAD

**Issue by pchq4205** [superwofy/E9X-M-CAN-Integration-Module#4]
Hello, 
i saw you Projekt and ported some of it to one of my "Special-Retrofits" in my Car. 
But i still dont understand one thing. How the Gyro emulation works. 
Do you have an easier understandable example how to implement random Values to get GPS to working. 
Because since the NBT Entrynav dont have an Build in Gyro i have to emulate something. 
(And i am using an Arduino Mega with the standart Can Bus shield) 
Thank you :) 
![photo_2024-06-11_09-07-18](https://github.com/superwofy/E9X-M-CAN-Integration-Module/assets/158815768/697303e1-79b5-422b-9fb8-90eaa6f889a6)
![photo_2024-06-11_09-07-29](https://github.com/superwofy/E9X-M-CAN-Integration-Module/assets/158815768/0f647ab7-2704-4a9b-bacf-6a7f0911818b)

**Comment by superwofy** [comment]
Hello,

The yaw rate is processed by the radio on CANID 0x2F3 or 0x19F. This is dependant on the gateway table coding. 0x2F3 for PL4-like cars, 0x19F for PL6. PL4: F20, F30, etc. PL6: F10, F11, etc.

If you look at function send_f_yaw_rate_chassis(), you will understand how it's encoded such that BMW radios understand it.

Your challenge will be to somehow obtain a lateral acceleration value from your VW and feed it to that function. Essentially substitute e_yaw_rate with your own degrees/s value. You could use an accelerometer if that is not available in your car.
